require('dotenv').config();
const express = require('express');
const cors = require('cors');
const summaryRoutes = require('./routes/summaryRoutes');
const { authRouter } = require('./googleAuth');
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/summary', summaryRoutes);
app.use('/auth/google', authRouter);
app.get('/', (req, res) => res.send('Backend is running'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server on https://ai-meeting-assistant-brhj.onrender.com:${PORT}`));
